// Auto-generated data for the Business Solutions gallery.
// Set isPlaceholder:false once a real photo has been placed at the matching filename.
const businessSolutions = [
  { name:"IoT Monitoring Platform", slug:"iot-monitoring-platform", cat:"IoT", icon:"🌐", desc:"Connected sensor networks with a live cloud dashboard for any monitoring need.", tech:"ESP32/STM32, Firebase / MQTT, responsive web dashboard", apps:"Facilities monitoring, cold-chain tracking, remote equipment status", isPlaceholder:true },
  { name:"Industrial Automation Systems", slug:"industrial-automation-systems", cat:"Industrial Automation", icon:"🏭", desc:"Sensor and relay-driven automation for repetitive industrial processes.", tech:"PLC-style embedded logic, relays, industrial sensors", apps:"Conveyor sorting, batch processing, safety interlocks", isPlaceholder:true },
  { name:"GPS Vehicle Tracking", slug:"gps-vehicle-tracking", cat:"GPS Tracking", icon:"📍", desc:"Real-time vehicle location, route history and geofence alerts — the same engine behind IshiTrackers.", tech:"ESP32, GPS/GSM modules, Firebase Realtime Database", apps:"Fleet management, logistics, school/staff transport safety", isPlaceholder:true },
  { name:"Asset Tracking Solutions", slug:"asset-tracking-solutions", cat:"Asset Tracking", icon:"📦", desc:"Track the location and status of high-value equipment and shipments.", tech:"BLE beacons / GPS trackers, cloud database", apps:"Warehouse inventory, equipment rental, container tracking", isPlaceholder:true },
  { name:"Energy Monitoring Systems", slug:"energy-monitoring-systems", cat:"Energy Monitoring", icon:"⚡", desc:"Live power-consumption tracking to identify waste and reduce electricity costs.", tech:"Current/voltage sensors, ESP32, analytics dashboard", apps:"Factories, commercial buildings, solar installations", isPlaceholder:true },
  { name:"Environmental Monitoring", slug:"environmental-monitoring", cat:"Environmental Monitoring", icon:"🌍", desc:"Air quality, temperature, humidity and pollution sensing networks.", tech:"Multi-sensor nodes, wireless mesh, cloud aggregation", apps:"Smart cities, agriculture, factory compliance monitoring", isPlaceholder:true },
  { name:"Data Logging Systems", slug:"data-logging-systems", cat:"Data Logging", icon:"💾", desc:"Reliable field data capture with local backup and cloud sync.", tech:"STM32/ESP32, SD card + cloud sync, RTC timestamping", apps:"Research instrumentation, quality control, remote sensing", isPlaceholder:true },
  { name:"Wireless Communication Systems", slug:"wireless-communication-systems", cat:"Wireless Communication", icon:"📡", desc:"Long-range and low-power wireless links for remote or hard-to-wire sites.", tech:"LoRa, GSM, Wi-Fi mesh networking", apps:"Remote sensing, agriculture, rural connectivity", isPlaceholder:true },
  { name:"Custom Embedded Systems", slug:"custom-embedded-systems", cat:"Custom Embedded Systems", icon:"🧩", desc:"Purpose-built firmware and hardware tailored exactly to your product requirement.", tech:"STM32/ESP32/AVR, RTOS, custom PCB", apps:"Product startups, OEM device manufacturers", isPlaceholder:true },
  { name:"Custom Electronics & Prototyping", slug:"custom-electronics-prototyping", cat:"Custom Electronics", icon:"🔧", desc:"From concept sketch to a working, testable prototype — full-stack hardware development.", tech:"Schematic design, PCB layout, 3D-printed enclosures", apps:"New product development, proof-of-concept builds, R&D", isPlaceholder:true }
];
