// Auto-generated project data for the Colleges gallery.
// Set isPlaceholder:false once a real photo has been placed at the matching filename.
const collegeProjects = [
  { name:"Smart Irrigation with ESP32", slug:"smart-irrigation-with-esp32", cat:"ESP32", tags:["ESP32","IoT"], icon:"🌾", level:"Major", problem:"Manual irrigation wastes water and depends on guesswork about soil conditions.", hw:"ESP32, capacitive soil moisture sensor, relay, water pump", sw:"Arduino IDE, Firebase Realtime Database", features:["Cloud-connected soil-moisture monitoring","Automatic pump control","Mobile alerts when watering occurs"], isPlaceholder:true },
  { name:"Home Automation via Wi-Fi", slug:"home-automation-via-wi-fi", cat:"IoT", tags:["IoT","ESP32"], icon:"🏠", level:"Mini", problem:"Traditional switches require physical presence to operate appliances.", hw:"ESP32/ESP8266, relay module, appliances", sw:"Blynk app or custom web dashboard", features:["Control appliances from anywhere","Voice-assistant integration possible","Simple, low-cost wiring"], isPlaceholder:true },
  { name:"STM32-Based Motor Controller", slug:"stm32-based-motor-controller", cat:"STM32", tags:["STM32","Embedded Systems"], icon:"⚙️", level:"Major", problem:"Open-loop motor control is inaccurate under changing load conditions.", hw:"STM32 Nucleo board, motor driver, DC motor, rotary encoder", sw:"STM32CubeIDE, PID control firmware", features:["Closed-loop PID speed control","Real-time encoder feedback","Stable performance under varying load"], isPlaceholder:true },
  { name:"GPS/GSM Vehicle Tracker", slug:"gps-gsm-vehicle-tracker", cat:"GPS/GSM", tags:["GPS/GSM","IoT"], icon:"📍", level:"Final Year", problem:"Fleet owners lack real-time visibility into vehicle location and status.", hw:"ESP32, GPS module, GSM/Wi-Fi connectivity", sw:"Firebase Realtime Database, live web dashboard", features:["Live location tracking","Geofencing and overspeed alerts","Same technology behind our IshiTrackers platform"], isPlaceholder:true },
  { name:"Bluetooth Controlled Robot", slug:"bluetooth-controlled-robot", cat:"Robotics", tags:["Robotics","Arduino"], icon:"🤖", level:"Mini", problem:"Demonstrating wireless robot control concepts for coursework.", hw:"Arduino Uno, HC-05 Bluetooth module, motor driver, chassis", sw:"Arduino IDE, Bluetooth terminal app", features:["Manual smartphone-based control","Simple serial communication protocol","Good base project for further robotics work"], isPlaceholder:true },
  { name:"Industrial Automation Demo", slug:"industrial-automation-demo", cat:"Automation", tags:["Automation","Embedded Systems"], icon:"🏭", level:"Major", problem:"Manual sorting/conveyor processes are slow and error-prone.", hw:"Arduino/ESP32, IR sensors, relays, conveyor model", sw:"Arduino IDE", features:["Sensor-triggered automated sorting","Scalable to real industrial scenarios","Demonstrates PLC-style logic in code"], isPlaceholder:true },
  { name:"LoRa-Based Long Range Sensor Node", slug:"lora-based-long-range-sensor-node", cat:"Wireless", tags:["Wireless","IoT"], icon:"📡", level:"Final Year", problem:"Wi-Fi and Bluetooth have limited range for remote-area sensing.", hw:"ESP32 + LoRa module, environmental sensors", sw:"Arduino IDE", features:["Multi-kilometre wireless range","Low power consumption","Ideal for agriculture/remote monitoring"], isPlaceholder:true },
  { name:"Smart Energy Meter", slug:"smart-energy-meter", cat:"IoT", tags:["IoT","Embedded Systems"], icon:"⚡", level:"Major", problem:"Manual meter readings are infrequent and don't show usage patterns.", hw:"ESP32, current/voltage sensor (ACS712/ZMPT101B)", sw:"Firebase, live dashboard", features:["Real-time power consumption monitoring","Historical usage graphs","Alerts for abnormal consumption"], isPlaceholder:true },
  { name:"Environmental Sensor Network", slug:"environmental-sensor-network", cat:"IoT", tags:["IoT","Wireless"], icon:"🌍", level:"Major", problem:"Single-point sensors don't capture how conditions vary across a large area.", hw:"Multiple ESP32 nodes, DHT/gas sensors", sw:"MQTT broker or Firebase Realtime Database", features:["Multi-node data collection","Centralised dashboard","Expandable node count"], isPlaceholder:true },
  { name:"Arduino-Based Attendance System", slug:"arduino-based-attendance-system", cat:"Arduino", tags:["Arduino","Embedded Systems"], icon:"🪪", level:"Mini", problem:"Manual attendance registers are slow and easy to falsify.", hw:"Arduino Uno, RFID reader/module, RTC module", sw:"Arduino IDE", features:["Fast RFID-based check-in","Timestamped logs via RTC","Exportable attendance records"], isPlaceholder:true },
  { name:"Line Following + Obstacle Avoiding Robot", slug:"line-following-obstacle-avoiding-robot", cat:"Robotics", tags:["Robotics"], icon:"🛣️", level:"Mini", problem:"Demonstrating combined sensor-fusion behaviour in a single robotics platform.", hw:"IR sensor array, ultrasonic sensor, motor driver, chassis", sw:"Arduino IDE", features:["Combines two classic robotics behaviours","Switchable operating modes","Popular for robotics competitions"], isPlaceholder:true },
  { name:"STM32 Data Logger with SD Card", slug:"stm32-data-logger-with-sd-card", cat:"STM32", tags:["STM32","Embedded Systems"], icon:"💾", level:"Mini", problem:"Sensor data needs reliable long-term storage for later analysis.", hw:"STM32 board, SD card module, sensors, RTC", sw:"STM32CubeIDE", features:["Timestamped data logging","Removable SD card storage","Low power standby mode"], isPlaceholder:true }
];
