// Auto-generated project data for the Schools gallery.
// Set isPlaceholder:false once a real photo has been placed at the matching filename.
const schoolProjects = [
  { name:"Automatic Street Light", slug:"automatic-street-light", icon:"💡", level:"Beginner", desc:"Streetlights that switch on by themselves as it gets dark outside.", components:"LDR (light sensor), Relay module, LED bulb, Arduino Uno, Jumper wires", learn:"How light sensors work, and how a computer chip can control a switch automatically.", isPlaceholder:true },
  { name:"Arduino Traffic Light", slug:"arduino-traffic-light", icon:"🚦", level:"Beginner", desc:"A working miniature traffic signal that cycles Red → Green → Yellow automatically.", components:"3 LEDs (Red, Yellow, Green), Resistors, Arduino Uno, Breadboard", learn:"Sequencing and timing logic — how real traffic signals coordinate to keep roads safe.", isPlaceholder:true },
  { name:"Smart Dustbin", slug:"smart-dustbin", icon:"🗑️", level:"Beginner", desc:"A dustbin whose lid opens automatically when your hand comes near it.", components:"Ultrasonic sensor, Servo motor, Arduino Uno, Dustbin body", learn:"Distance sensing and how to move a motor to a precise angle using code.", isPlaceholder:true },
  { name:"Water Level Indicator", slug:"water-level-indicator", icon:"💧", level:"Beginner", desc:"Warns you with a buzzer when a water tank is almost full or almost empty.", components:"Water level sensor strip, Buzzer, LEDs, Arduino Uno", learn:"Analog sensing and how to set safe threshold values for alerts.", isPlaceholder:true },
  { name:"Obstacle Avoiding Robot", slug:"obstacle-avoiding-robot", icon:"🤖", level:"Intermediate", desc:"A robot car that senses obstacles ahead and steers around them by itself.", components:"Ultrasonic sensor, Motor driver (L298N), 2 DC motors, Chassis kit, Arduino Uno", learn:"Robotics fundamentals — combining sensing and motor control to create autonomous behaviour.", isPlaceholder:true },
  { name:"Line Following Robot", slug:"line-following-robot", icon:"🛣️", level:"Intermediate", desc:"A robot that follows a black line drawn on the floor, all on its own.", components:"IR sensor array, Motor driver, 2 DC motors, Chassis kit, Arduino Uno", learn:"Feedback control — how a robot corrects its own path in real time.", isPlaceholder:true },
  { name:"Automatic Plant Watering", slug:"automatic-plant-watering", icon:"🌱", level:"Beginner", desc:"Waters your plant by itself whenever the soil gets too dry.", components:"Soil moisture sensor, Mini water pump, Relay module, Arduino Uno, Water tubing", learn:"Environmental sensing and simple automation that solves a real everyday problem.", isPlaceholder:true },
  { name:"Fire Alarm", slug:"fire-alarm", icon:"🔥", level:"Beginner", desc:"Sounds a loud alarm the moment it detects flame or excess heat.", components:"Flame sensor, Buzzer, LED, Arduino Uno", learn:"Safety-focused sensing and how quick alerts can prevent accidents.", isPlaceholder:true },
  { name:"Rain Alarm", slug:"rain-alarm", icon:"🌧️", level:"Beginner", desc:"Detects raindrops and sounds an alert so you know it's started raining.", components:"Rain sensor module, Buzzer, Arduino Uno", learn:"Analog thresholds — deciding at what sensor value an action should trigger.", isPlaceholder:true },
  { name:"Temperature & Humidity Monitor", slug:"temperature-humidity-monitor", icon:"🌡️", level:"Beginner", desc:"Shows the current room temperature and humidity on a small display.", components:"DHT11 sensor, 16x2 LCD display, Arduino Uno", learn:"Digital sensors and how to show live readings on a screen.", isPlaceholder:true },
  { name:"Smart Home Model", slug:"smart-home-model", icon:"🏠", level:"Intermediate", desc:"A tabletop model home showing lights, fans and doors controlled automatically.", components:"Relays, Sensors (light/motion), LED bulbs, mini fan, Arduino Uno", learn:"How multiple sensors and outputs can be combined into a complete automation system.", isPlaceholder:true },
  { name:"Digital Notice Board", slug:"digital-notice-board", icon:"📋", level:"Intermediate", desc:"A scrolling display board that shows messages and announcements.", components:"LED matrix display or 16x2 LCD, Arduino Uno", learn:"Text display techniques and how information can be shown digitally instead of on paper.", isPlaceholder:true },
  { name:"Mini Security Alarm", slug:"mini-security-alarm", icon:"🚨", level:"Beginner", desc:"Triggers a loud alarm if a door or window is opened without permission.", components:"Reed switch or IR sensor, Buzzer, Arduino Uno", learn:"Basic switches and how they can be used to build simple security systems.", isPlaceholder:true },
  { name:"Mini Robotic Car", slug:"mini-robotic-car", icon:"🚗", level:"Beginner", desc:"A simple remote or app-controlled car built from scratch with Arduino.", components:"Motor driver, 2-4 DC motors, Bluetooth module, Chassis kit, Arduino Uno", learn:"Basic motor control and wireless communication between a phone and a microcontroller.", isPlaceholder:true },
  { name:"Solar Tracking System", slug:"solar-tracking-system", icon:"☀️", level:"Intermediate", desc:"Tilts a solar panel automatically to always face the brightest direction.", components:"LDR sensors (x2), Servo motor, small solar panel, Arduino Uno", learn:"How renewable energy systems can be made more efficient using simple sensing.", isPlaceholder:true }
];
